### ISSUE TITLE
socks代理设置

### ISSUE THREAD

**Issue by A1130155732** [Chihiro23333/MoeLoaderFlutter#1]
请问下大佬，socks代理是不支持吗还是有特殊格式。显示信号灯超时
![捕获](https://github.com/Chihiro23333/MoeLoaderFlutter/assets/163630583/d3c38206-9fb7-410a-b8ae-07bdd3a9f847)

**Comment by Chihiro23333** [comment]
我这边试了好像是可以的，代理需要在右上角的设置按钮里面配置下，可以贴一下你的代理地址配置看下是否正确，以下是我的配置地址：
![PixPin_2024-03-19_14-13-36](https://github.com/Chihiro23333/MoeLoaderFlutter/assets/19475100/7d8fd515-6115-4304-a208-38024d78b556)
@A1130155732

**Comment by Chihiro23333** [comment]
已添加SOCKS代理支持，请更新代码或者下载最新的Release版本(V1.0.2)。
@A1130155732

**Comment by A1130155732** [comment]
感谢大佬！
